# Generated by Django 6.1.1 on 2026-09-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField(unique=True)),
                ('category', models.CharField(choices=[('Latest Jobs', 'Latest Jobs'), ('Result', 'Result'), ('Admit Card', 'Admit Card'), ('Answer Key', 'Answer Key'), ('Admission', 'Admission'), ('Syllabus', 'Syllabus'), ('Documents', 'Documents'), ('10th/ITI Jobs', '10th/ITI Jobs'), ('Outsourcing Jobs', 'Outsourcing Jobs')], default='Latest Jobs', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
