# Generated by Django 6.1.1 on 2026-09-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Latest Jobs', 'Latest Jobs'), ('Result', 'Result'), ('Admit Card', 'Admit Card'), ('Answer Key', 'Answer Key'), ('Documents', 'Documents'), ('Admission', 'Admission'), ('10th/ITI Jobs', '10th/ITI Jobs'), ('Outsourcing Jobs', 'Outsourcing Jobs'), ('Syllabus', 'Syllabus')], max_length=100),
        ),
    ]
