# Generated by Django 6.1.1 on 2026-09-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age_relaxation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='application_last_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='application_start',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='apply_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='eligibility',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='exam_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='female_fee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='general_fee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='maximum_age',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='minimum_age',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='notification_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='official_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sc_st_fee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='selection_process',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='vacancy_details',
            field=models.TextField(blank=True),
        ),
    ]
