# Generated by Django 6.1.1 on 2026-09-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_age_relaxation_post_application_last_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discover Item',
                'verbose_name_plural': 'Discover Items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
