# Generated by Django 6.1.1 on 2026-09-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_is_automated_post_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ews_fee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='exam_date_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='obc_fee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='result_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='result_link',
            field=models.URLField(blank=True),
        ),
    ]
