# Generated by Django 6.1.1 on 2026-09-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_ews_fee_post_exam_date_link_post_obc_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='exam_mode',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20),
        ),
    ]
