# Generated by Django 6.1.1 on 2026-09-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_exam_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_vacancies',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
