# Generated by Django 6.1.1 on 2026-09-21 17:01

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='admit_card_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='correction_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='how_to_apply',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='How To Apply'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_details',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Post Details'),
        ),
        migrations.AddField(
            model_name='post',
            name='syllabus',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Syllabus'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='eligibility',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Eligibility'),
        ),
        migrations.AlterField(
            model_name='post',
            name='selection_process',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Selection Process'),
        ),
        migrations.AlterField(
            model_name='post',
            name='vacancy_details',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Vacancy Details'),
        ),
    ]
