# Generated by Django 6.1.1 on 2026-09-21 17:14

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_admit_card_date_post_correction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='age_relaxation',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Age Relaxation'),
        ),
        migrations.AlterField(
            model_name='post',
            name='maximum_age',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Maximum Age'),
        ),
        migrations.AlterField(
            model_name='post',
            name='minimum_age',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Minimum Age'),
        ),
    ]
