# Generated by Django 6.1.1 on 2026-09-21 17:29

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_age_relaxation_alter_post_maximum_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Answer')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='posts.post')),
            ],
            options={
                'verbose_name': 'Post FAQ',
                'verbose_name_plural': 'Post FAQs',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
