# Generated by Django 6.1.1 on 2026-09-22 10:15

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_postfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answer_key',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='answer_key_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='syllabus_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
